[features]
resolution = true
skip-lint = false

[programs.localnet]
discount_platform = "kCBLrJxrFgB7yf8R8tMKZmsyaRDRq8YmdJSG9yjrSNe"



[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"


[scripts]
#test = "cargo test"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

